    # Set default expect fallback routines
expect_after {
    eof {
        if {[info exists test]} {
            fail "$test at eof" 
        } else {
            fail "[info level 1] at eof" 
        }; # if
    }; # eof
    timeout {
        if {[info exists test]} {
            fail "$test at timeout" 
        } else {
            fail "[info level 1] at timeout" 
        }; # if
    }; # timeout
}; # expect_after()


    # Call tool_start(), if available
if { [info procs "${tool}_start"] != "" } {
    ${tool}_start
}; # if
