# Set default expect fallback routines
expect_after {
    eof {
        if {[info exists test]} {
            fail "$test at eof" 
        } else {
            fail "[info level 1] at eof" 
        }
    }
    timeout {
        if {[info exists test]} {
            fail "$test at timeout" 
        } else {
            fail "[info level 1] at timeout" 
        }
    }
}


# Call tool_start(), if available
if { [info procs "${tool}_start"] != "" } {
    ${tool}_start
}
