# cd(1) completion

_comp_cmd_cd__compgen_cdable_vars()
{
    shopt -q cdable_vars || return 1

    local vars
    _comp_compgen -v vars -- -v || return "$?"

    # Remove variables that do not contain a valid directory path.
    local _i
    for _i in "${!vars[@]}"; do
        # Note: ${!vars[_i]} produces the "nounset" error when vars[_i] is an
        # empty array name.
        [[ -d ${!vars[_i]-} ]] || unset -v 'vars[_i]'
    done

    _comp_compgen -U vars set "${vars[@]}"
}

# This generator function observes the CDPATH variable, to additionally
# complete directories under those specified in CDPATH.
_comp_cmd_cd__compgen_cdpath()
{
    local _p

    # Generate CDPATH completions when the parameter does not start with /,
    # ./ or ../
    [[ ! ${CDPATH-} || $cur == ?(.)?(.)/* ]] && return 1

    local _mark_dirs="" _mark_symdirs=""
    _comp_readline_variable_on mark-directories && _mark_dirs=set
    _comp_readline_variable_on mark-symlinked-directories && _mark_symdirs=set

    local -a _cdpaths=()

    # we have a CDPATH, so loop on its contents
    local paths dirs _d
    _comp_split -F : paths "$CDPATH"
    for _p in "${paths[@]}"; do
        _p="${_p:-.}"
        # create an array of matched subdirs
        _comp_compgen -v dirs -c "$_p/$cur" -- -d &&
            for _d in "${dirs[@]}"; do
                if [[ ($_mark_symdirs && -L $_d || $_mark_dirs && ! -L $_d) && ! -d ${_d#"$_p/"} ]]; then
                    _d+="/"
                fi
                _cdpaths+=("${_d#"$_p/"}")
            done
    done
    _comp_unlocal paths dirs

    ((${#_cdpaths[@]})) &&
        _comp_compgen_set "${_cdpaths[@]}"
}

_comp_cmd_cd()
{
    local cur prev words cword comp_args
    _comp_initialize -- "$@" || return

    if [[ $cur == -* ]]; then
        _comp_compgen_help -c help "$1"
        compopt +o nospace
        return
    fi

    compopt -o filenames
    _comp_cmd_cd__compgen_cdable_vars

    # A directory of the current directory that is also reachable through
    # CDPATH is generated by both of the generators below, so collect their
    # results in a separate array and drop the duplicates before adding them
    # to COMPREPLY.  This also has to happen before the sole-completion
    # adjustment below, which would otherwise see one directory as two and
    # suffix only one of the two spellings with a slash.
    local -a matches=()
    local cdpath_matched=""
    _comp_compgen -v matches -i cd cdpath && cdpath_matched=set
    _comp_compgen -av matches filedir -d

    if ((${#matches[@]} > 1)); then
        local -A seen=()
        local -a uniq=()
        local match
        for match in "${matches[@]}"; do
            [[ ${seen[$match]-} ]] && continue
            seen[$match]=set
            uniq+=("$match")
        done
        matches=("${uniq[@]}")
    fi

    # When a CDPATH directory is the only completion and it is already fully
    # typed, suffix it with a slash so that completion can descend into it.
    # This cannot be left to readline's mark-directories, which does not
    # recognize a CDPATH directory missing from the current directory as a
    # directory, and which may be turned off altogether.
    if [[ $cdpath_matched ]] && ((${#matches[@]} == 1)) &&
        [[ ${matches[0]} == "$cur" && ${matches[0]} != */ ]]; then
        matches[0]+=/
    fi

    ((${#matches[@]})) && COMPREPLY+=("${matches[@]}")
}
complete -F _comp_cmd_cd -o nospace cd pushd
