#!/bin/bash -eu

# Generate skeleton files for completion of specified command.

shopt -s extglob

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 command [args...]" >&2
    exit 1
fi

cmd=$1
file=$1
arg=${2-}
name=
marker=

[[ $arg == +(-) ]] && name=dash
[[ $arg == *(-)+([a-zA-Z0-9]) ]] && name=${arg##+(-)}

if [[ $cmd == *.* ]]; then
    file=${cmd//./-}
    marker=$'\n'"@pytest.mark.command(\"$cmd\")"
fi

cat <<EOF >t/test_$file.py
import pytest

$marker
class Test(object):

    @pytest.mark.complete("$1 $arg")
    def test_$name(self, completion):
        assert completion.list
EOF

tmpfile=$(mktemp)
trap "{ rm -f $tmpfile; }" EXIT
in_extra_dist=
added=
IFS=$'\n'
while read -r line; do
    if [[ $in_extra_dist ]]; then
        if [[ $line != $'\t'* ]]; then
            if [[ ! $added ]]; then
                echo -e "\ttest_$file.py \\"
                added=true
            fi
            in_extra_dist=
        elif [[ ! $added && $line > $'\t'test_$file.py ]]; then
            echo -e "\ttest_$file.py \\"
            added=true
        fi
        echo "$line"
    else
        if [[ $line == EXTRA_DIST\ * ]]; then
            in_extra_dist=true
        fi
        echo "$line"
    fi
done < t/Makefile.am > $tmpfile && mv -f $tmpfile t/Makefile.am
