#!/bin/bash -eu

# Generate skeleton files for completion of specified command.

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 command" >&2
    exit 1
fi

cat <<EOF >t/test_$1.py
import pytest


class Test(object):

    @pytest.mark.complete("$1 ")
    def test_(self, completion):
        assert completion.list
EOF
