#!/bin/bash -eu

mydir=$(cd "$(dirname "$0")"; pwd)

cat "$mydir"/t/test_*.py \
    | tr -d '\n' \
    | grep -Eo '@pytest.mark.complete(\([^)]*\))' \
    | sed -e 's/^[^"]*"\\\?\([^[:space:]"]*\)[[:space:]"].*/\1/' \
    | sort -u \
    > "$mydir"/test-cmd-list.txt
