source lib/library.exp


proc completion_exit {} {
        # Exit bash
    send "\rexit\r"
}; # completion_exit()


proc completion_start {} {
    global TESTDIR TOOL_EXECUTABLE spawn_id
    set test "completion_start"
    set TESTDIR [pwd]

        # Start bash and load bash-completion

    # If `--tool_exec' option not specified, use "bash"
    if {! [info exists TOOL_EXECUTABLE]} {set TOOL_EXECUTABLE bash}
    exp_spawn $TOOL_EXECUTABLE --rcfile config/bashrc
    assert_bash_exec {} "$TOOL_EXECUTABLE --rcfile config/bashrc"
    assert_bash_exec {BASH_COMPLETION_DIR=$(cd ..; pwd)/contrib}
    assert_bash_exec {BASH_COMPLETION=$(cd ..; pwd)/bash_completion}
    assert_bash_exec {source $BASH_COMPLETION}
}; # completion_start()


proc completion_version {} {
    puts "bash-completion-git"
}
