source lib/library.exp


proc completion_exit {} {
        # Exit bash
    send "\rexit\r"
}; # completion_exit()


proc completion_start {} {
    global TESTDIR spawn_id
    set test "completion_start"
    set TESTDIR [pwd]

        # Start bash and load bash-completion

    exp_spawn bash --rcfile config/bashrc
    assert_bash_exec {} "bash --rcfile config/bashrc"
    assert_bash_exec {BASH_COMPLETION_DIR=$(cd ..; pwd)/contrib}
    assert_bash_exec {BASH_COMPLETION=$(cd ..; pwd)/bash_completion}
    assert_bash_exec {source $BASH_COMPLETION}
}; # completion_start()


proc completion_version {} {
    puts "bash-completion-git"
}
