source lib/library.exp


proc unit_exit {} {
        # Exit bash
    send "\rexit\r"
}; # unit_exit()


proc unit_start {} {
    global TESTDIR TOOL_EXECUTABLE spawn_id
    set test "unit_start"
    set TESTDIR [pwd]

        # Start bash and load bash-completion

    # If `--tool_exec' option not specified, use "bash"
    if {! [info exists TOOL_EXECUTABLE]} {set TOOL_EXECUTABLE bash}
    exp_spawn $TOOL_EXECUTABLE --rcfile config/bashrc
    assert_bash_exec {} "$TOOL_EXECUTABLE --rcfile config/bashrc"
    assert_bash_exec {BASH_COMPLETION_DIR=$(cd ..; pwd)/contrib}
    assert_bash_exec {BASH_COMPLETION=$(cd ..; pwd)/bash_completion}
    # Bash < 3.2.41 has a bug where 'history' disappears from SHELLOPTS
    # whenever a shopt setting is sourced or eval'ed.  Disabling 'history'
    # makes it not show in tests "Environment should not be modified"
    # for bash < 3.2.41.
    # -- FVu, Tue Sep 15 22:52:00 CEST 2009
    assert_bash_exec {is_bash_version_minimal 3 2 41 || set +o history}
    assert_bash_exec {source $BASH_COMPLETION}
}; # unit_start()


proc unit_version {} {
    puts "bash-completion-git"
}
