proc setup {} {
}; # setup()


proc teardown {} {
}; # teardown()


setup


set test "Tab should complete"
    # Try completion
set cmd "apt-get "
send "$cmd\t"
expect {
    -re	"$cmd\r\nautoclean\\s+autoremove\\s+build-dep\\s+check\\s+clean\\s+dist-upgrade\\s+dselect-upgrade\\s+install/\r\npurge\\s+remove\\s+source\\s+update\\s+upgrade\\s*\r\n/@$cmd$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}; # expect


sync_after_int


teardown
