proc setup {} {
}; # setup()


proc teardown {} {
}; # teardown()


setup


set test "Tab should complete"
    # Try completion
set cmd "bc --"
send "$cmd\t"
  # NOTE: Wait in case `bc' isn't installed, so that "^$cdm$" doesn't match
  #       before comp_install has finished
sleep .5
expect {
    -re "^$cmd\r\n.*$cmd$" { pass "$test" }
    -re "^$cmd$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}; # expect


sync_after_int


teardown
