proc setup {} {
    set test setup
    set cmd "touch fixture1/t.{pdf,PDF,{,e}ps,{,E}PS}";  # Create temporary files
    send "$cmd\r"
    expect -ex "$cmd\r\n/@"
}; # setup()


proc teardown {} {
    set test teardown
    set cmd "rm fixture1/t.{pdf,PDF,{,e}ps,{,E}PS}";  # Remove temporary files
    send "$cmd\r"
    expect -ex "$cmd\r\n/@"
}; # teardown()


setup


set test "Tab should complete kpdf"
    # Try completion
set cmd "kpdf fixture1/"
send "$cmd\t"
expect {
    -re "^${cmd}\r\n(\.svn/ +|)bar bar.d/ +foo.d/ +(\.svn/ +|)t.eps +t.EPS +t.pdf +t.PDF +t.ps +t.PS *\r\n/@$cmd$"  { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    default { unresolved "$test" }
}; # expect


sleep .5
sync_after_int


teardown
