proc setup {} {
}; # setup()


proc teardown {} {
}; # teardown()


setup


set test "Tab should complete"
    # Try completion
set cmd "mkisofs "
send "$cmd\t"
expect {
    -re "^$cmd\r\n.*$cmd$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}; # expect


sync_after_int


set test "-uid should complete uids"
    # Try completion
set cmd "mkisofs -uid "
send "$cmd\t"
expect {
    -re "^$cmd\r\n\\d+.*$cmd$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}; # expect


sync_after_int


set test "-gid should complete gids"
    # Try completion
set cmd "mkisofs -gid "
send "$cmd\t"
expect {
    -re "^$cmd\r\n\\d+.*$cmd$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}; # expect


sync_after_int


teardown
