proc setup {} {
}; # setup()


proc teardown {} {
}; # teardown()


setup


set test "Tab should complete"
    # Try completion
set cmd "removepkg "
send "$cmd\t"
  # NOTE: Wait in case `kldload' isn't installed, so that "^$cdm.*$" doesn't match
  #       before comp_install has finished
sleep .4
expect {
    -re "^$cmd.*$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}; # expect


sync_after_int


teardown
