proc setup {} {
}; # setup()


proc teardown {} {
}; # teardown()


setup


set test "Tab should complete"
    # Try completion
set cmd "reportbug --m"
send "$cmd\t"
expect {
    -re "^$cmd\r\n.*$cmd$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}; # expect


sync_after_int


set test "Completing --editor should invoke _command"
    # Try completion
set cmd "reportbug --editor vim"
send "$cmd\t"
expect {
    -re "^$cmd\r\n.*$cmd$" { pass "$test" }
    -re "^$cmd\r\n.*$cmd$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}; # expect


sync_after_int


teardown
