proc setup {} {
}; # setup()


proc teardown {} {
}; # teardown()


setup


set test "Tab should complete"
    # Try completion
set cmd "sysctl "
send "$cmd\t"
  # NOTE: Wait in case `sysctl' returns nothing, so that "^$cdm.*$" doesn't match
  #       too early -- before comp_install has finished
sleep 1 
expect {
    -re "^$cmd\.*$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}; # expect


sync_after_int


teardown
