#!/bin/sh

set -e

case "$1" in
    configure)
	ucf /usr/share/bash/bash_completion /etc/bash_completion
	ucfr bash-completion /etc/bash_completion
	;;
    abort-upgrade|abort-remove|abort-deconfigure)
	;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
