proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified {/OLDPWD=/d}
}


setup


assert_complete_any "7z "
sync_after_int


assert_complete "-tzip" "7z a ar -tzi"
sync_after_int


set dir $::srcdir/fixtures/_filedir
assert_complete_dir "-wa\\ b/" "7z x -wa\\ " $dir "" -nospace
sync_after_int


set dir $::srcdir/fixtures/7z
assert_complete_dir "a.7z" "7z x " $dir
sync_after_int


set dir $::srcdir/fixtures/7z
assert_complete_dir "abc" "7z d a.7z " $dir
sync_after_int


teardown
