proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified {/OLDPWD=/d}
}


setup


set test "Tab should complete commands"
set cmd "apt-get "
send "$cmd\t"
set expected "^$cmd\r\n.* install .* update .*\r\n/@$cmd$"
expect {
    -re $expected { pass "$test" }
    default { fail "$test" }
}
sync_after_int


assert_complete_dir "./bash-completion-test-subject.deb" "apt-get install ./" "$::srcdir/fixtures/dpkg"
sync_after_int


teardown
