proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


assert_complete_any "ccache -"
sync_after_int


set test "Tab should offer correct options from partial option"
assert_complete_partial [list "--cleanup" "--clear"] "ccache" "--clea" $test
sync_after_int


set test "Tab should complete a command after ccache"
assert_complete [list "stty"] "ccache stt" $test
sync_after_int


set test "Tab should complete a command after ccache --FLAG"
assert_complete [list "stty"] "ccache --zero-stats stt" $test
sync_after_int


set test "Tab should complete a command's flags after ccache"
assert_complete [list "--help"] "ccache ls --hel" $test
sync_after_int


set test "Tab should complete a command's flags after ccache --FLAG"
assert_complete [list "--help"] "ccache --zero-stats ls --hel" $test
sync_after_int


teardown
