proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


assert_complete_any "chkconfig -"
sync_after_int


# systemd may not be running e.g. in a docker container, and listing services
# will then fail.
if {[assert_exec {systemctl list-units} "" "" "unsupported" ]} {
    # TODO test this also if systemctl command is not available at all
    assert_complete_any "chkconfig "
}
sync_after_int


teardown
