proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


assert_complete_any "cppcheck "
sync_after_int


assert_complete_any "cppcheck -"
sync_after_int


assert_complete_any "cppcheck -DFOO=BAR "
sync_after_int


assert_no_complete "cppcheck -D "
sync_after_int


assert_complete "--enable=all" "cppcheck --enable=al"
sync_after_int


assert_complete "--enable=xx,style" "cppcheck --enable=xx,styl"
sync_after_int


assert_complete "--enable=xx,yy,style" "cppcheck --enable=xx,yy,styl"
sync_after_int


teardown
