proc setup {} {
    save_env
    assert_bash_exec {OLDHOME=$HOME ; HOME=$SRCDIR/fixtures/cvs}
}


proc teardown {} {
    assert_bash_exec {HOME=$OLDHOME}
    assert_env_unmodified {
        /OLDHOME=/d
        /OLDPWD=/d
    }
}


setup


assert_complete_any "cvs "


sync_after_int


set test "-d should complete CVS roots"
set cmd "cvs -d "
send "$cmd\t"
expect {
    -re "^$cmd\r\n.*:pserver:.*\r\n/@$cmd:pserver:.*$" { pass "$test" }
    default { fail "$test" }
}


sync_after_int


assert_complete_dir "foo/bar" "cvs diff foo/" $::srcdir/fixtures/cvs
sync_after_int


teardown
