proc setup {} {
    save_env
    assert_bash_exec {OLDHOME=$HOME ; HOME=$TESTDIR/fixtures/cvs}
}; # setup()


proc teardown {} {
    assert_bash_exec {HOME=$OLDHOME}
    assert_env_unmodified {
        /OLDHOME=/d
    }
}; # teardown()


setup


assert_complete_any "cvsps -"


sync_after_int


set test "No arguments should complete CVS roots"
set cmd "cvsps "
send "$cmd\t"
expect {
    -re "^$cmd\r\n.*:pserver:.*\r\n/@$cmd:pserver:.*$" { pass "$test" }
    default { fail "$test" }
}; # expect


sync_after_int


teardown
