proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


assert_complete_any "display "


sync_after_int


set test "- should complete options"
set options {
    -alpha -antialias -authenticate -auto-orient -backdrop -background -border
    -bordercolor -borderwidth -channel -clip -clip-path -coalesce -colormap
    -colors -colorspace -comment -compress -contrast -crop -debug -decipher
    -define -delay -density -depth -despeckle -display -dispose -dither -edge
    -endian -enhance -extract -filter -flatten -flip -flop -font -foreground
    -format -frame -gamma -geometry -help -iconGeometry -iconic -identify
    -immutable -interlace -interpolate -label -limit -list -log -loop -map
    -mattecolor -monitor -monochrome -name -negate -page -profile -quality
    -quantize -quiet -raise -regard-warnings -remote -repage -resample -resize
    -respect-parenthesis -roll -rotate -sample -sampling-factor -scenes -seed
    -segment -set -shared-memory -sharpen -size -strip -texture -title
    -transparent-color -treedepth -trim -update -usePixmap -verbose -version
    -virtual-pixel -visual -window -window-group -write }
assert_complete $options "display -" $test


sync_after_int


teardown
