proc setup {} {
    save_env
}; # setup()


proc teardown {} {
    assert_env_unmodified
}; # teardown()


setup


assert_complete_any "dpkg --c"


sync_after_int


    # Build list of installed packages
    # NOTE: If an argument is passed to `--get-selections', `dpkg' also returns
    #       packages with status "purged".  Be sure to add `| grep install$' to
    #       pipeline before 'cut' in that case. -- FVu, Sun Feb 22 10:08:34 CET 2009
if {[assert_exec {dpkg --get-selections | cut -f1} packages]} {
    assert_complete $packages "dpkg -L "
}; # if


sync_after_int


teardown
