proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified {/OLDPWD=/d}
}


setup


set test "should complete *.t\[gbxl\]z files and dirs"
set dir $::srcdir/fixtures/slackware/home
set files [split [exec bash -c "cd $dir && find . -mindepth 1 -maxdepth 1 \
           \\( -type d -printf '%P/\\n' \\) -o \
           \\( -type f -name '*.t\[bglx\]z' -printf '%P\\n' \\)"] "\n"]
assert_complete_dir $files "explodepkg " $dir $test


sync_after_int


teardown
