proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


assert_complete_any "feh "


sync_after_int


set test "--lis<TAB> should complete \"--list\""
assert_complete "--list" "feh --lis" $test


sync_after_int


set test "-S pix<TAB> should complete \"pixels\""
assert_complete "pixels" "feh -S pix" $test


sync_after_int


set test "--zoom ma<TAB> should complete \"max\""
assert_complete "max" "feh --zoom ma" $test


sync_after_int


set test "-g 640<TAB> should complete digits plus \"x\""
assert_complete "0 1 2 3 4 5 6 7 8 9 x" "feh -g 640" $test


sync_after_int


set test "-g 640x48<TAB> should complete digits"
assert_complete "0 1 2 3 4 5 6 7 8 9" "feh -g 640x48" $test


sync_after_int


teardown
