proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified {
        /OLDPWD=/d
    }
}


setup


assert_complete_any "htpasswd "
sync_after_int


assert_no_complete "htpasswd -n $::srcdir/fixtures/htpasswd/ht"
sync_after_int


assert_complete_dir "htpasswd" "htpasswd " $::srcdir/fixtures/htpasswd
sync_after_int


assert_complete_dir "foo quux" "htpasswd -D htpasswd " $::srcdir/fixtures/htpasswd
sync_after_int


teardown
