proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified {/OLDPWD=/d}
}


setup


assert_complete_any "installpkg -"


sync_after_int


set test "--<TAB> should complete all long options"
set options [list --warn --md5sum --root --infobox --terse --menu --ask \
                  --priority --tagfile]
assert_complete $options "installpkg --" $test


sync_after_int


set test "--root should comlete only dirs"
set dirs [split [exec bash -c "find . -type d -mindepth 1 -maxdepth 1 \
                                      -printf '%P/\n'"] "\n"]
assert_complete $dirs "installpkg --root " $test


sync_after_int


set test "should complete *.t\[gbxl\]z files and dirs"
set dir $::srcdir/fixtures/slackware/home
set files [split [exec bash -c "cd $dir && find . -mindepth 1 -maxdepth 1 \
           \\( -type d -printf '%P/\\n' \\) -o \
           \\( -type f -name '*.t\[bglx\]z' -printf '%P\\n' \\)"] "\n"]
assert_complete_dir $files "installpkg " $dir $test


sync_after_int


teardown
