proc setup {} {
    assert_bash_exec {CLASSPATH=$TESTDIR/fixtures/java/a:$TESTDIR/fixtures/java/bashcomp.jar}
    save_env
}; # setup()


proc teardown {} {
    assert_env_unmodified
}; # teardown()


setup


assert_complete_any "java -"


sync_after_int


assert_complete "b bashcomp.jarred toplevel" "java "


sync_after_int


assert_complete "bashcomp.jarred toplevel" \
    "java -cp $TESTDIR/fixtures/java/bashcomp.jar "


sync_after_int


assert_no_complete "java -cp \"\" "


sync_after_int


teardown
