proc setup {} {
    assert_bash_exec {CLASSPATH=$SRCDIR/fixtures/java/a:$SRCDIR/fixtures/java/bashcomp.jar}
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


assert_complete_any "java -"


sync_after_int


assert_complete "b bashcomp.jarred toplevel" "java "


sync_after_int


assert_complete "bashcomp.jarred toplevel" \
    "java -cp $::srcdir/fixtures/java/bashcomp.jar "


sync_after_int


assert_no_complete "java -cp \"\" "


sync_after_int


assert_complete "a/ bashcomp.jar" "java -jar $::srcdir/fixtures/java/"


sync_after_int


teardown
