proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


assert_complete_any "kcov "


sync_after_int


set test "--<TAB> should complete all long options"
set options [list --help --pid= --sort-type= --limits= --title= --include-path=\
                  --exclude-path= --include-pattern= --exclude-pattern=]
assert_complete $options "kcov --" $test


sync_after_int


teardown
