proc setup {} {
    save_env
}; # setup()


proc teardown {} {
    assert_env_unmodified {/OLDPWD=/d}
}; # teardown()


setup


# NOTE: The directory `fixtures/kdvi' contains an additional subdir `foo'
#       (should be visible as completion) and an additional file `.txt'
#       (shouldn't be visible as completion)
set files {
    foo/
    .dvi  .DVI  .dvi.bz2  .DVI.bz2  .dvi.gz  .DVI.gz  .dvi.Z  .DVI.Z
}
assert_complete_dir $files "kdvi " "fixtures/kdvi"


sync_after_int


teardown
