proc setup {} {
    save_env
}; # setup()


proc teardown {} {
    assert_env_unmodified {/OLDPWD=/d}
}; # teardown()


setup


# NOTE: The directory `fixtures/kpdf' contains an additional subdir `foo'
#       (should be visible as completion) and an additional file `.txt'
#       (shouldn't be visible as completion)
set files {
    foo/ .eps .ps .EPS .PS .pdf .PDF
}
assert_complete_dir $files "kpdf " "fixtures/kpdf"


sync_after_int 


teardown
