proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


set test "~part should complete to ~full<space> if home dir does not exist"
# Create list of users, having non-existing home dir
assert_bash_exec {for u in $(compgen -u); do \
    eval test -d ~$u || echo $u; unset u; done} {} /@ users
if {![find_unique_completion_pair $users part full]} {
    untested "Not running, no suitable test user found: $test"
} else {
    assert_complete "~$full " "ls ~$part" $test -nospace
}
sync_after_int


teardown
