proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


if {[assert_exec {ls --help} "" "" "unsupported"]} {
    assert_complete_any "ls --"
}


sync_after_int


set test "~part should complete to ~full/ if existing dir"
# Create list of users, having existing home dir
assert_bash_exec {for u in $(compgen -u); do \
    eval test -d ~$u && echo $u; unset u; done} {} /@ users
find_unique_completion_pair $users part full
assert_complete "~$full/" "ls ~$part" $test -nospace


sync_after_int


set test "~part should complete to ~full<space> if non-existing dir"
# Create list of users, having non-existing home dir
assert_bash_exec {for u in $(compgen -u); do \
    eval test -d ~$u || echo $u; unset u; done} {} /@ users
find_unique_completion_pair $users part full
assert_complete "~$full " "ls ~$part" $test -nospace


sync_after_int


teardown
