proc setup {} {
    assert_bash_exec "export MANPATH=$::srcdirabs/fixtures/man:$::srcdirabs/tmp/man"
    save_env

    if {! [is_cygwin]} {  # Colon not allowed in filenames
        assert_bash_exec {(cd $TESTDIR/tmp && mkdir -p man/man3 && touch man/man3/Bash::Completion.3pm.gz || true)}
    }
}


proc teardown {} {
    assert_env_unmodified {
        /OLDPWD/d
        /OLDMANPATH/d
    }

    if {! [is_cygwin]} {
        assert_bash_exec {(cd $TESTDIR/tmp && rm -r man || true)}
    }
}


setup


if {! [is_cygwin]} {
    assert_complete "Bash::Completion" "man Bash::C"
    sync_after_int
}


teardown
