proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


assert_complete_any "mkdir "


sync_after_int


assert_complete {"bar bar.d/" foo.d/} "mkdir $::srcdir/fixtures/shared/default/"


sync_after_int


# No subdirs in foo.d and should not complete files in it (_longopt()).
assert_no_complete "mkdir $::srcdir/fixtures/shared/default/foo.d/"


sync_after_int


teardown
