proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


assert_complete_any "mkdir "


sync_after_int


assert_complete {bar "bar bar.d/" foo foo.d/} "mkdir $::srcdir/fixtures/shared/default/"


sync_after_int


set test "mkdir should complete files with nospace"
assert_complete {foo} "mkdir $::srcdir/fixtures/shared/default/foo.d/" $test -nospace


sync_after_int


teardown
