proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


assert_complete_any "mkisofs "


sync_after_int


set test "-uid should complete uids"
    # Try completion
set cmd "mkisofs -uid "
send "$cmd\t"
expect {
    -re "^$cmd\r\n\\d+.*$cmd$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}


sync_after_int


set test "-gid should complete gids"
    # Try completion
set cmd "mkisofs -gid "
send "$cmd\t"
expect {
    -re "^$cmd\r\n\\d+.*$cmd$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}


sync_after_int


teardown
