proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}

setup

assert_complete_any "mr "
sync_after_int

assert_complete_any "mr --"
sync_after_int

assert_complete {"foo"} "mr -c $::srcdir/fixtures/shared/default/foo.d/"
sync_after_int

assert_complete {"bar bar.d/" "foo.d/"} "mr -d $::srcdir/fixtures/shared/default/"
sync_after_int

assert_complete {"bar" "bar bar.d/" "foo" "foo.d/"} "mr bootstrap $::srcdir/fixtures/shared/default/"
sync_after_int

assert_complete "-f" "mr clean -"
sync_after_int

assert_complete "-m" "mr commit -"
sync_after_int

assert_no_complete "mr status "
sync_after_int

teardown
