proc setup {} {
    save_env
    assert_bash_exec {OLDHOME=$HOME ; HOME=$SRCDIRABS/fixtures/mutt}
}


proc teardown {} {
    assert_bash_exec {HOME=$OLDHOME}
    assert_env_unmodified {
        /OLDPWD=/d
        /OLDHOME=/d
    }
}


setup


assert_complete_any "mutt -"


sync_after_int


set test "mutt should complete mailboxes" 
set expected {foo/ bar/ muttrc}
assert_complete_dir $expected "mutt -F muttrc -f =" $::srcdir/fixtures/mutt $test


set test "mutt should complete aliases" 
set expected {a1 a2}
assert_complete_dir $expected "mutt -F muttrc -A " $::srcdir/fixtures/mutt $test


sync_after_int


set expected "$::srcdirabs/fixtures/mutt/muttrc $::srcdirabs/fixtures/mutt/bar/muttrc_b $::srcdirabs/fixtures/mutt/foo/muttrc_f"
assert_bash_list $expected { _muttconffiles "$HOME/muttrc" "$HOME/muttrc" } "find muttrcs recursively"
sync_after_int


teardown
