proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


set test "perldoc should complete word containing colons"
set cmd "perldoc File::"
send "$cmd\t"
expect {
    # Assuming the module `File::Path' is always installed
    -re "\\sPath\\s" { pass "$test" }
    # Assuming there's no perl module named `fixtures', but only our directory
    # `test/fixtures' which is presented falsely.
    -re "\\sfixtures/\\s" { fail "$test" }
    -re "perldoc File::File::" { fail "$test" }
    -re /@ { unresolved "$test" }
    default { unresolved "$test" }
}
sync_after_int


assert_complete_any "perldoc -"
sync_after_int


teardown
