proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified {/PERL5LIB=/d}
}


setup


# Make sure at least our mock Devel::* module is around
assert_bash_exec {OLDPERL5LIB=$PERL5LIB; export PERL5LIB=$TESTDIR/fixtures/perl}

assert_complete_any "perl -d:"
sync_after_int

assert_complete_any "perl -dt:"
sync_after_int

assert_bash_exec {export PERL5LIB=$OLDPERL5LIB; unset -v OLDPERL5LIB}

teardown
