proc setup {} {
    assert_bash_exec {PORTSDIR=$TESTDIR/tmp; sed -e s,PORTSDIR,$PORTSDIR,g $::srcdir/fixtures/pkgtools/ports/INDEX.dist > $PORTSDIR/INDEX; cp $PORTSDIR/INDEX $PORTSDIR/INDEX-5}
    save_env
}


proc teardown {} {
    assert_bash_exec {rm $PORTSDIR/INDEX $PORTSDIR/INDEX-5}
    assert_env_unmodified
}


setup


assert_complete "bash-2.05b.007_6 bash-3.1.17 bash-completion-20060301_2 shells/bash shells/bash-completion shells/bash2" "portinstall "


sync_after_int


teardown
