proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup

# Broken configs may abort output of postconf halfway through, so use
# something from early output to not trigger false positives because of
# this. For example, inet_protocols=all but no IPv6 configured:
# postconf: fatal: parameter inet_interfaces: no local interface found for ::1
# ...and output can be cut off somewhere near lmtp_tls_secur*.
# ...or be completely missing, so all we can do is to skip.
set test "\"postconf al\" should complete al* variables"
if {[assert_exec {postconf} "" "" "untested"]} {
    assert_complete_any "postconf al"
}
sync_after_int

assert_complete_any "postconf -"
sync_after_int


teardown
