proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


assert_complete_any "python "
sync_after_int

assert_complete_any "python -"
sync_after_int

assert_no_complete "python -c "
sync_after_int

assert_complete {"bar bar.d/" foo.d/} "python $::srcdir/fixtures/shared/default/"
sync_after_int

assert_complete {bar "bar bar.d/" foo foo.d/} "python -c foo $::srcdir/fixtures/shared/default/"
sync_after_int

assert_no_complete "python -c foo -"
sync_after_int

assert_no_complete "python -m foo -"
sync_after_int

assert_complete_any "python -m sy"
sync_after_int

assert_complete_any "python -m json."
sync_after_int

assert_complete_any "python -W "
sync_after_int

assert_complete_any "python -Wa"
sync_after_int


teardown
