proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


set test "Tab should show complete process ids"
    # Try completion
set cmd "renice 1"
send "$cmd\t"
expect {
    -re "$cmd\r\n\\d+.*/@$cmd$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}


sync_after_int


set test "Tab should show complete process group ids"
    # Try completion
set cmd "renice -g "
send "$cmd\t"
expect {
    -re "$cmd\r\n\\d+.*/@$cmd$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}


sync_after_int


teardown
