proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified {/OLDPWD=/d}
}


setup


assert_complete_any "rpm2tgz -"


sync_after_int


set test "should complete *.rpm files and dirs"
set dir $::srcdir/fixtures/slackware/home
set files [split [exec bash -c "cd $dir && find . -mindepth 1 -maxdepth 1 \
           \\( -type d -printf '%P/\\n' \\) -o \
           \\( -type f -name '*.rpm' -printf '%P\\n' \\)"] "\n"]
assert_complete_dir $files "rpm2tgz " $dir $test


sync_after_int


teardown
