proc setup {} {
    save_env
    # NOTE: Changing dir to $SRCDIR is necessary because file locations in the
    #       ssh config files (e.g. UserKnownHostsFile) are relative to $SRCDIR.
    assert_bash_exec {cd $SRCDIR/fixtures/scp}
}


proc teardown {} {
    assert_bash_exec {cd $TESTDIR}
    assert_env_unmodified {
        /BASH_LINENO=/d
        /BASH_SOURCE=/d
        /OLDPWD=/d
    }
}


setup


set test "Tab should complete remote pwd"
set host bash_completion

    # Retrieving home directory (host_pwd) from ssh-host `bash_completion'
    # yields error?
if {
    [catch {
	exec -- ssh -o "Batchmode yes" -o "ConnectTimeout 1" $host pwd 2>>/dev/null
    } host_pwd]
} {
    # Yes, retrieving pwd from ssh yields error; reset `host_pwd'
        # Indicate host pwd is unknown and test is unsupported
        # NOTE: To support this test, set the hostname "bash_completion"
        #       in `$HOME/.ssh/config' or `/etc/ssh_config'
    set host_pwd ""
    unsupported $test
}


    # Try completion
set cmd "scp $host:"
send "$cmd\t"
sync_after_tab
expect {
    -re "^$cmd$host_pwd.*$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
}


sync_after_int


assert_bash_exec {cd "$TESTDIR"}


sync_after_int


teardown
