proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified {/OLDPWD=/d}
}


setup


assert_complete_any "screen -"
sync_after_int


assert_complete {bar "bar bar.d/" foo foo.d/} \
    "screen -c $::srcdir/fixtures/shared/default/" "-c should complete files/dirs"
sync_after_int


assert_complete_any "screen cat"
sync_after_int


assert_complete_any "screen -T foo cat"
sync_after_int


teardown
