proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


assert_complete_any "slapt-get -"


sync_after_int


set test "--up<TAB> should complete \"--update --upgrade\""
assert_complete "--update --upgrade" "slapt-get --up" $test


sync_after_int


set test "--install should not complete anything if config doesn't exist"
assert_no_complete "slapt-get -c non-existent-file --install " $test


sync_after_int


set test "--install should complete available packages"
set config $::srcdir/fixtures/slackware/etc/slapt-get/slapt-getrc
set workdir [file normalize $::srcdir/fixtures/slackware/var/slapt-get/]
set pkg_data "$workdir/package_data"
# write simple config
set f [open $config w]
puts $f "WORKINGDIR=$workdir"
puts $f "SOURCE=file:///home/"
close $f
set packages [split [exec bash -c "sed -n \
      '/^PACKAGE NAME:/{s/^PACKAGE NAME: \\{1,\\}\\(.*\\).t\[gbxl\]z/\\1/;p}' \
      $pkg_data"] "\n"]
assert_complete $packages "slapt-get -c $config --install " $test


sync_after_int


teardown
