proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


assert_complete_any "slapt-src -"


sync_after_int


set test "--bu<TAB> should complete \"--build\""
assert_complete "--build" "slapt-src --bu" $test


sync_after_int


set test "--ins<TAB> should complete \"--install\""
assert_complete "--install" "slapt-src --ins" $test


sync_after_int


set test "--install should complete available packages"
set config $::srcdir/fixtures/slackware/etc/slapt-get/slapt-srcrc
set workdir [file normalize $::srcdir/fixtures/slackware/usr/src/slapt-src/]
set slb_data "$workdir/slackbuilds_data"
set f [open $config w]; puts $f "BUILDDIR=$workdir"; close $f
set slackbuilds [split [exec bash -c "sed -n \
        -e '/^SLACKBUILD NAME: /{s/^SLACKBUILD NAME: \\{1,\\}//;p}' \
        -e '/^SLACKBUILD VERSION: /{s/^SLACKBUILD VERSION: \\{1,\\}//;p}' \
        $slb_data | sed -e 'N;s/\\n/:/'"] "\n"]
assert_complete $slackbuilds "slapt-src --config $config --install " $test


sync_after_int


teardown
