proc setup {} {
    save_env
}

proc teardown {} {
    assert_env_unmodified {
        /OLDPWD=/d
        /declare -f _tar/d
    }
}

setup

set test "old option: list escaped chars"
assert_complete_dir "a/b\\'c/" "tar tf escape.tar a/b\\\'" $::srcdir/fixtures/tar $test
sync_after_int

# TODO: "tar tf escape.tar a/b"

# Use bsdtar as the it completes to only 'zc zt zx' ('tar' can be GNU tar and it
# can would have more options)
set test "old option: mode is not on first place"
assert_complete {zc zt zx} "bsdtar z" $test
sync_after_int

set test "old option: check _second_ option in \"old\" argument"
assert_complete_dir "dir/ dir2/" "bsdtar cbfvv NOT_EXISTS " $::srcdir/fixtures/tar
sync_after_int

teardown
