proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


set test "Testing internal __linux_fstab_unescape function for umount"
# One round of slashes is for bash.
assert_bash_exec {var=one\'two\\040three\\}
assert_bash_exec {__linux_fstab_unescape var}
set cmd {echo $var}
send "$cmd\r"
expect {
    -ex "$cmd\r\none'two three\\" { pass $test }
#    default { fail $test }
}
sync_after_int
assert_bash_exec {unset var}


sync_after_int


teardown
