proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified {/OLDPWD=/d}
}


setup


set test "should complete *.exe, *.com files and dirs"
set dir $::srcdir/fixtures/shared/default
assert_complete_dir {"bar bar.d/" foo.d/} "wine " $dir $test


sync_after_int


set test "should complete any files and dirs after executable"
set dir $::srcdir/fixtures/shared/default
set files {bar "bar bar.d/" foo foo.d/}
assert_complete_dir $files "wine notepad " $dir $test


sync_after_int


teardown
