proc setup {} {
    # See fixtures/shared/bin/{arp,ifconfig}
    assert_bash_exec {OLDPATH="$PATH"; PATH="$TESTDIR/fixtures/shared/bin:$PATH";}
    save_env
}; # setup()


proc teardown {} {
    assert_env_unmodified
    assert_bash_exec {PATH="$OLDPATH"; unset -v OLDPATH}
}; # teardown()


setup


assert_complete "00:00:00:00:00:00 11:11:11:11:11:11 22:22:22:22:22:22 33:33:33:33:33:33" "wol "


sync_after_int


# XXX: Why does this fail?  It completes to "00:00:00:00:00:00:00"
# XXX: (one "00:" too many, apparently added to front).
# XXX: "wol 00" works as expected.
assert_complete "00:00:00:00:00:00" "wol 00:"


sync_after_int


teardown
