proc setup {} {
    # See fixtures/shared/bin/{arp,ifconfig}
    assert_bash_exec {OLDPATH="$PATH"; PATH="$SRCDIR/fixtures/shared/bin:$PATH";}
    save_env
}


proc teardown {} {
    assert_env_unmodified
    assert_bash_exec {PATH="$OLDPATH"; unset -v OLDPATH}
}


setup


assert_complete "00:00:00:00:00:00 11:11:11:11:11:11 22:22:22:22:22:22 33:33:33:33:33:33" "wol "


sync_after_int


assert_complete "00:00:00:00:00:00" "wol 00:"


sync_after_int


teardown
