proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


assert_complete_any "xdg-mime "
sync_after_int

assert_complete_any "xdg-mime -"
sync_after_int

assert_complete_any "xdg-mime query "
sync_after_int

assert_complete_any "xdg-mime query filetype "
sync_after_int

assert_complete_any "xdg-mime query default "
sync_after_int

assert_complete_any "xdg-mime default foo.desktop "
sync_after_int

assert_complete_any "xdg-mime install --mode "
sync_after_int

assert_complete_any "xdg-mime uninstall "
sync_after_int


teardown
