proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified
}


setup


set test "Tab should complete options"
set options {
    -AcceptClipboard -AutoSelect -DebugDelay -display
    -DotWhenNoCursor -FullColor -FullColour -FullScreen
    -geometry -help -listen -Log
    -LowColourLevel -MenuKey -name -Parent
    -passwd -PasswordFile -PointerEventInterval -PreferredEncoding
    -SendClipboard -SendPrimary -Shared -UseLocalCursor
    -via -ViewOnly -WMDecorationHeight -WMDecorationWidth
    -ZlibLevel
}
assert_complete $options {vncviewer -} $test


sync_after_int


set expected {hextile raw zrle}
assert_complete $expected "xvnc4viewer -PreferredEncoding "


sync_after_int


set expected {hextile raw zrle}
assert_complete $expected "xvnc4viewer --preferredencoding "


sync_after_int


teardown
