FROM centos:6

# TODO: more coverage
# /usr/bin/which: https://bugzilla.redhat.com/show_bug.cgi?id=1443357
RUN yum -y install \
        autoconf \
        automake \
        dejagnu \
        tcllib \
        /usr/bin/xvfb-run /usr/bin/which

WORKDIR /usr/src/bash-completion
COPY . .
