FROM vskytta/bash-completion:fedoradev

# When adding new completions, install packages desired for their testing here
# in case they're not in the base image, and remove later when the base image
# has caught up.
#RUN dnf --nogpgcheck --refresh -y install \
#        some-package

WORKDIR /work
COPY . .
CMD ["bash"]
