proc setup {} {
    save_env
}


proc teardown {} {
    assert_env_unmodified {/OLDPWD/d}
}


setup


set test {compgen -f a\\\'b/ should return a\'b/c}
set cmd {compgen -f a\\\'b/}
set dir $::srcdir/fixtures/compgen
assert_bash_exec "cd $dir"
send "$cmd\r"
expect -ex "$cmd\r\n"
expect {
    -re {a\\\'b/c} { pass $test }
    -re {a'b/c} { fail $test }
    -re /@ { pass "$test" }
    -re eof { unresolved "eof" }
}
sync_after_int
assert_bash_exec {cd "$TESTDIR"}

#assert_bash_list_dir {a\\\'b/c} $cmd $::srcdir/fixtures/compgen


sync_after_int


teardown
