#!/usr/bin/env bash
set -euo pipefail

is_tracked_by_git()
{
    git ls-files --error-unmatch "$1" &>/dev/null
}

cd "$(dirname "$0")/completions"
for f in *; do
    if [[ -L $f ]] && is_tracked_by_git "$f"; then
        git rm -f "$f"
    fi
done
for f in ../../../completions-fallback/*.bash; do
    if is_tracked_by_git "$f"; then
        ln -sf "$f" "${f##*/}"
        git add --verbose "${f##*/}"
    fi
done
