name: Lint commits

on:
  pull_request:

permissions: {}

jobs:
  lint-commits:
    name: Lint commits
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: true
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: crate-ci/committed@faeed42f2e10c244533a01525f13c4d8b6ce383f # v1.1.11
        with:
          args: "-vv --no-merge-commit --config=.config/committed.toml"
